In [1]:
print "built-in type"

three = float(3)

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-1-d43c9c43a6aa>, line 1)

In [2]:
print ("built-in type")

three = float(3)

built-in type


In [3]:
three

3.0

In [4]:
Three=int(3)
three

3.0

In [5]:
Three

3

In [6]:
x=3
y=6
x*y

18

In [7]:
abs(3-5)

2

In [8]:
print ("PhD Candidate Yafie Zhang")

PhD Candidate Yafie Zhang


In [9]:
num_list=[1,2,3,4,5,6,7,8]
#I defined a list of numbers

In [10]:
num_list

[1, 2, 3, 4, 5, 6, 7, 8]

In [11]:
num_list[::3]
#This operater chooses a number from the list (num_list) which is a multiple of 3, so the 0 and the 3rd, and the 6th. So 1, 4, and 7

[1, 4, 7]

NameError: name 'numlist' is not defined

In [13]:
num_list[::-3]

[8, 5, 2]

In [14]:
num_list.reverse

<function list.reverse>

In [15]:
num_list.reverse()


In [16]:
num_list

[8, 7, 6, 5, 4, 3, 2, 1]

In [17]:
#U see the difference dumb ass!! Here, the reversal is permenant 

In [1]:
Dummy=True
# This is defining a dummy variable that has a true value,i.e. positive indicator 

In [3]:
type(Dummy)
#I'm asking what is the type of this variabe, it is called a Booleans variable

bool

In [6]:
Dummy==1
#When I state the variable (Dummy) has a positive indicator, the answer is 'True'

True

In [7]:
x= 'State'
# I defined a variable 'x' that has a srting value 'State'

In [10]:
print(x)

State


In [11]:
x

'State'

In [12]:
x[-1]
#What is the last character in the variable 'x'

'e'

In [13]:
print(x[-1])

e


In [14]:
x+': South Carolina'
#Adding a string to a string variable 

'State: South Carolina'

In [16]:
print(x+': South Carolina')

State: South Carolina


In [20]:
print((x+': South Carolina')[-2])
#WPrint the second last letter in the function: 'x+...'

n


In [21]:
x*2
#the content of the string variable printed twice

'StateState'

In [23]:
y=3
y*2
#Here the function multiplies 3 by 2 since the variable is an integer rather than a string

6

In [24]:
z='3'
z*2
#See how 3 is a string now, so it prints it twice rather than multiplying

'33'

In [27]:
x.upper()
#Upper cases all the characters in the string variable x


'STATE'

In [28]:
x.lower()
#Lower cases all the characters in the string variable x

'state'

In [33]:
## '''Lists lists are ordered collections of objects these objects can be different types. 
#but usually a list contains similarly typed objects lists are 'mutable', which means they can 
#change after they have been created


SyntaxError: invalid syntax (<ipython-input-33-07fdb4a63701>, line 2)

In [34]:
numlist=[1, 2, 3, 4, 5]

In [35]:
print(numlist)

[1, 2, 3, 4, 5]


In [36]:
numlist

[1, 2, 3, 4, 5]

In [37]:
state_name=['South Carolina','Indiana', 'Washington']

In [38]:
print(state_name)

['South Carolina', 'Indiana', 'Washington']


In [39]:
#Lists accepts duplicate values, while sets do not
numlist=[1,1,1,1,3,4]
numlist

[1, 1, 1, 1, 3, 4]

In [40]:
numset={1, 1, 1, 1, 3, 4}
numset

{1, 3, 4}

In [41]:
#lists accepts numeric and string values:
numlist+state_name

[1, 1, 1, 1, 3, 4, 'South Carolina', 'Indiana', 'Washington']

In [42]:
print(numlist+state_name)

[1, 1, 1, 1, 3, 4, 'South Carolina', 'Indiana', 'Washington']


In [43]:
numlist.remove(1)
#removes an obersvation with a value =1, note it removes only 1 of the 1s
print(numlist)

[1, 1, 1, 3, 4]


In [44]:
state_name.remove('Washington')
print(state_name)

['South Carolina', 'Indiana']


In [45]:
del(numlist[2])
# this code deletes the number 2 element in the list (numlist). Note the first element is counted as 0, so technecally,
#2 is the third element
print(numlist)

[1, 1, 3, 4]


In [46]:
##Tuples
#Tuples are ordered collections of objects. 
#Tuples are immutable. Tuples more often contain heterogenous types of objects.

In [47]:
num_tup=(1,1,2,4)
num_tup
#Dublicates are fine here

(1, 1, 2, 4)

In [48]:
num_tup[0]
#calling the first element from the tuple

1

In [49]:
numlist[3]

4

In [50]:
numset[1]
#Indexing here won't work. So lists and tuples are fine, but sets .. nada!

TypeError: 'set' object does not support indexing

In [51]:
for i in num_tup:
    print(i)
#This creates a variable i that goes all the way in the tuples. It works for lists too!

1
1
2
4


In [52]:
for i in numset:
    print(i)
#Works for sets too!!

1
3
4


In [57]:
range(100,120,1)
#This is a function that generates numbers from 100 to before 120, increasing in increments of 1

range(100, 120)

In [58]:
for i in range(100,120,1):
    print(i)

100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119


In [59]:
#Lets try increments of less than 1:
for i in range(100,110,0.5):
    print(i)

    #Nope! 

TypeError: 'float' object cannot be interpreted as an integer

In [60]:
#LHow about increments of more than 1:
for i in range(100,110,2):
    print(i)
    
#Yup!, so the increment has to be an integer

100
102
104
106
108


In [61]:
#Sets are unordered collection of unique values. They are mutable. Useful for membership testing, uniqueness tests

print(numset)

{1, 3, 4}


In [62]:
2 in numset
#Testing whether 2 is in the set

False

In [63]:
4 in numset

True

In [64]:
numset.remove(3)
#See here you can use remove but you cannot use the del(var[x]) cuz the set is in a specific order
#So if you want to delete an element, then you need to use var.remove(the value)
numset

{1, 4}

# Using NumPy Broadcasting

In [3]:
import numpy as np

In [4]:
#see Yafie's note for an example of arrays and multipications


In [5]:
# if arrays are not in the same size, we use numpy boradcasting. Numpy will make the two arrays broadcast together

In [6]:
B = np.array([2, 5])

In [7]:
A = np.array([[1,2],[3,4]])

In [8]:
A * B

array([[ 2, 10],
       [ 6, 20]])

In [9]:
B.shape

(2,)

In [15]:
C = np.array([1, 2, 1])
C

array([1, 2, 1])

In [14]:
A * C
#Won't be broadcasts here

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [16]:
# NumPy and special arrays

In [17]:
#Matricies of all ones
np.ones(2)

array([ 1.,  1.])

In [18]:
np.ones((2, 2))

array([[ 1.,  1.],
       [ 1.,  1.]])

In [19]:
np.zeros((2,2))

array([[ 0.,  0.],
       [ 0.,  0.]])

In [20]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [21]:
#Reshaping Arrays
A.reshape((4,1))

# from 2 by 2 to 4 by 1
#Note A was not replaced

array([[1],
       [2],
       [3],
       [4]])

In [22]:
D = np.tile(A, (1, 1, 4))

#Tiling an existing matrix with additional values



In [23]:
D

array([[[1, 2, 1, 2, 1, 2, 1, 2],
        [3, 4, 3, 4, 3, 4, 3, 4]]])

In [24]:
D.shape

(1, 2, 8)

In [26]:
D = np.tile(A.reshape((2, 2, 1)),(1, 1, 4))

In [27]:
D.shape

(2, 2, 4)

# Pandas
A package that helps to work with panel data. Its the leading package for data python.
Kind of making a 2 demention object (columns and rows, like stata)
It has the ability to index in multidemensional data in 2D

In [28]:
import pandas as pd

In [30]:
#To understand pandas, lets enter data manually, so we will create a dictionary and put values manually

data = {'school': ['Texas', 'Texas', 'Texas', 'UGA', 'UGA'], 'year': [2014, 2015, 2016, 2015, 2016], 
        'wins': [6, 5, 5, 10, 8]}
data

{'school': ['Texas', 'Texas', 'Texas', 'UGA', 'UGA'],
 'wins': [6, 5, 5, 10, 8],
 'year': [2014, 2015, 2016, 2015, 2016]}

In [32]:
frame = pd.DataFrame(data)
#I want to make a pandas frame with the dictionary (data)

frame

school  wins  year
0  Texas     6  2014
1  Texas     5  2015
2  Texas     5  2016
3    UGA    10  2015
4    UGA     8  2016

In [33]:
#What are the variable names of this frame
frame.columns

Index(['school', 'wins', 'year'], dtype='object')

In [34]:
#Or we can do:
list(frame)

['school', 'wins', 'year']

In [35]:
#To refrence a particular column, IT IS CASE SENSITIVE!! The first column is the observation number
frame['wins']

0     6
1     5
2     5
3    10
4     8
Name: wins, dtype: int64

In [36]:
#Pulling a particular row in the dictionary
frame.loc[0]

school    Texas
wins          6
year       2014
Name: 0, dtype: object

In [37]:
frame.loc[1:3]
# show data from obs 1 to 3

school  wins  year
1  Texas     5  2015
2  Texas     5  2016
3    UGA    10  2015

In [38]:
frame.loc[0, 'school']

#The value of row 0 and under column school

'Texas'

In [39]:
frame.groupby(['school'])['wins'].sum()

school
Texas    16
UGA      18
Name: wins, dtype: int64

In [40]:
frame.describe()
#summary stats, its doing it for every variable
#u can configure what vars or how it is displayed basd on what you put between the peranthesis 

wins        year
count   5.000000     5.00000
mean    6.800000  2015.20000
std     2.167948     0.83666
min     5.000000  2014.00000
25%     5.000000  2015.00000
50%     6.000000  2015.00000
75%     8.000000  2016.00000
max    10.000000  2016.00000

In [41]:
frame['wins squared'] = frame['wins'] **2
#Creating a new variable from wins and squaring it

frame

school  wins  year  wins squared
0  Texas     6  2014            36
1  Texas     5  2015            25
2  Texas     5  2016            25
3    UGA    10  2015           100
4    UGA     8  2016            64

In [43]:
#If the dataset is so big, and you want a peak, say only 2 rows
frame.head(n=2)

school  wins  year  wins squared
0  Texas     6  2014            36
1  Texas     5  2015            25

In [47]:
#renaming a column
frame.rename(columns={"wins": "Wins", "wins squared": "win sqr"}, inplace = True)

# Using CSV in Python

In [48]:
import csv

In [49]:
kisa_data = list(csv.reader(open('kisa_2015.csv')))
#inputing the data set . ITS ADDING EVERYTHING AS A STRING VAR

In [52]:
# see number of obs in the data set
len(kisa_data)

96

In [53]:
# Another way to let the program knows which var is string or numeric using numpy

In [54]:
kisa_data = np.genfromtxt('kisa_2015.csv', delimiter=",")

kisa_data[:5]

array([[             nan,              nan,              nan,
                     nan,              nan,              nan,
                     nan,              nan,              nan,
                     nan,              nan,              nan,
                     nan,              nan,              nan,
                     nan,              nan,              nan,
                     nan,              nan,              nan,
                     nan,              nan,              nan,
                     nan,              nan,              nan,
                     nan,              nan,              nan,
                     nan,              nan,              nan,
                     nan,              nan,              nan,
                     nan],
       [  1.20000000e+01,   4.20000000e+01,   5.00000000e+00,
          5.70000000e+01,   4.00000000e+00,   1.00000000e+00,
          1.40000000e+01,   4.00000000e+01,   1.00000000e+00,
          5.70000000e+01,   4.93400000e+04,

In [55]:
# Not reading it correctly(Handeled numeric well, but not string vars), and some are missing...


In [57]:
kisa_data = pd.read_csv('kisa_2015.csv')

#We use pandas to read the data now

In [59]:
kisa_data.head(5)

month  grdatn  marstat  age  class  region  state  hours  mlr  natvty  \
0     12      42        5   57      4       1     14     40    1      57   
1     12      39        7   26      4       1     14     40    1      57   
2     12      41        1   43      4       2     41     46    1     110   
3     12      39        1   38      4       2     41     40    1      57   
4     12      42        1   51     -1       3     58     -1    6      57   

      ...      homeown  hoursu1b  hoursu1b_t1  se15u  se15u_t1  ent015u  \
0     ...          NaN        40           40      0         0      0.0   
1     ...          NaN        40           40      0         0      0.0   
2     ...          NaN        46           40      0         0      0.0   
3     ...          NaN        40           30      0         0      0.0   
4     ...          NaN        -1           -1      0         0      0.0   

   ent015ua  vet       wgtat      wgtat1  
0       0.0    0  269.172442  270.433824  
1       0.0    0  403.023478  404.912105  
2       0.0    0  402.790075  404.677609  
3       0.0    0  342.934489  344.541531  
4       0.0    0  560.224448  562.849743  

[5 rows x 37 columns]

In [60]:
kisa_data['age'].mean()

#mean of the column named 'age'

43.17894736842105

In [61]:
kisa_data.describe()

month     grdatn    marstat        age      class     region  \
count   95.0  95.000000  95.000000  95.000000  95.000000  95.000000   
mean    12.0  40.284211   2.568421  43.178947   2.810526   3.210526   
std      0.0   2.562675   2.434908  11.816846   2.531902   0.921317   
min     12.0  34.000000   1.000000  20.000000  -1.000000   1.000000   
25%     12.0  39.000000   1.000000  33.500000  -1.000000   3.000000   
50%     12.0  40.000000   1.000000  44.000000   4.000000   3.000000   
75%     12.0  43.000000   5.000000  52.000000   4.000000   4.000000   
max     12.0  46.000000   7.000000  64.000000   7.000000   4.000000   

           state      hours        mlr      natvty     ...      homeown  \
count  95.000000  95.000000  95.000000   95.000000     ...          0.0   
mean   69.084211  27.673684   2.557895   88.473684     ...          NaN   
std    23.262454  21.014403   2.499854   79.168799     ...          NaN   
min    14.000000  -1.000000   1.000000   57.000000     ...          NaN   
25%    63.000000  -1.000000   1.000000   57.000000     ...          NaN   
50%    71.000000  40.000000   1.000000   57.000000     ...          NaN   
75%    86.000000  41.500000   5.500000   57.000000     ...          NaN   
max    94.000000  65.000000   7.000000  364.000000     ...          NaN   

        hoursu1b  hoursu1b_t1      se15u   se15u_t1  ent015u  ent015ua  \
count  95.000000    95.000000  95.000000  95.000000     87.0      85.0   
mean   27.315789    27.221053   0.073684   0.084211      0.0       0.0   
std    20.111531    20.316212   0.262642   0.279177      0.0       0.0   
min    -1.000000    -1.000000   0.000000   0.000000      0.0       0.0   
25%    -1.000000    -1.000000   0.000000   0.000000      0.0       0.0   
50%    40.000000    40.000000   0.000000   0.000000      0.0       0.0   
75%    40.000000    40.000000   0.000000   0.000000      0.0       0.0   
max    65.000000    70.000000   1.000000   1.000000      0.0       0.0   

             vet       wgtat      wgtat1  
count  95.000000   95.000000   95.000000  
mean    0.084211  320.829357  322.332811  
std     0.279177  127.035039  127.630344  
min     0.000000   40.806662   40.997888  
25%     0.000000  244.629113  245.775481  
50%     0.000000  351.493054  353.140203  
75%     0.000000  405.081462  406.979734  
max     1.000000  600.702105  603.517084  

[8 rows x 36 columns]

# Writing a function
function is like a macro variable in SAS

In [62]:
def product(val1, val2):
    prod = val1 * val2
    
    return prod

# a macro called product that has two inputs, value 1 and value 2, the function does value 1 times value 2. 
#Then return the result of the function



In [63]:
x, y = 4, 5
# I defined x as 4 and y as 5, (two definintions in 1, more effecient)

In [64]:
product(x,y)
# I used the function I created 'product'

20